// https://oj.leetcode.com/problems/subsets-ii/

// Iterative: when we find number same with the last one, we should
// push new results only based on the last inserted results.
// http://www.cnblogs.com/TenosDoIt/p/3451902.html
class Solution {
public:
    vector<vector<int> > subsetsWithDup(vector<int> &S) {
        int size = static_cast<int>(S.size());
        vector<vector<int> > ret;
        vector<int> tmp;
        
        sort(S.begin(), S.end());
        ret.push_back({});
        int last_index = -1;
        for (int i = 0; i < size; i++) {
            int start = 0;
            int retsize = ret.size();
            
            if (i > 0 && S[i] == S[i-1]) {
                start = last_index;
            }
            for (int j = start; j < retsize; j++) {
                vector<int> t = ret[j];
                t.push_back(S[i]);
                ret.push_back(t);
            } 
            
            last_index = retsize; // beginning result index generated by this iteration
        }
        
        return ret;
    }
}; 

// Recursion
class Solution {
    void subsets_of(int n, vector<int> &S, int start, const int size,
                    vector<vector<int> > &result, vector<int> &one_result) {
        if (n == 0) {
            result.push_back(one_result);
            return;
        }
        
        for (int i = start; i < size; i++) {
            if (i > start && S[i] == S[i - 1]) {
                continue;
            }
            one_result.push_back(S[i]);
            subsets_of(n - 1, S, i + 1, size, result, one_result);
            one_result.pop_back();
        }
    }
    
public:
    vector<vector<int> > subsetsWithDup(vector<int> &S) {
        int size = static_cast<int>(S.size());
        vector<vector<int> > ret;
        vector<int> tmp;
        
        sort(S.begin(), S.end());
        for (int i = 0; i <= size; i++) {
            subsets_of(i, S, 0, size, ret, tmp);
        }
        
        return ret;
    }
};